/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PrivateLayoutRouteImport } from './pages/_private/layout'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as PrivateUsersIndexRouteImport } from './pages/_private/users/index'
import { Route as PrivateNewslettersIndexRouteImport } from './pages/_private/newsletters/index'
import { Route as PrivateCategoriesIndexRouteImport } from './pages/_private/categories/index'
import { Route as PrivateArticlesIndexRouteImport } from './pages/_private/articles/index'
import { Route as PrivateAccountIndexRouteImport } from './pages/_private/account/index'
import { Route as PrivateOverviewIndexRouteImport } from './pages/_private/_overview/index'
import { Route as PrivateArticlesSlugRouteImport } from './pages/_private/articles/$slug'
import { Route as PrivateArticlesNewIndexRouteImport } from './pages/_private/articles/new/index'

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateUsersIndexRoute = PrivateUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateNewslettersIndexRoute = PrivateNewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateCategoriesIndexRoute = PrivateCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateArticlesIndexRoute = PrivateArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateAccountIndexRoute = PrivateAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateOverviewIndexRoute = PrivateOverviewIndexRouteImport.update({
  id: '/_overview/',
  path: '/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateArticlesSlugRoute = PrivateArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateArticlesNewIndexRoute = PrivateArticlesNewIndexRouteImport.update({
  id: '/articles/new/',
  path: '/articles/new/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateOverviewIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/articles/$slug': typeof PrivateArticlesSlugRoute
  '/account/': typeof PrivateAccountIndexRoute
  '/articles/': typeof PrivateArticlesIndexRoute
  '/categories/': typeof PrivateCategoriesIndexRoute
  '/newsletters/': typeof PrivateNewslettersIndexRoute
  '/users/': typeof PrivateUsersIndexRoute
  '/articles/new/': typeof PrivateArticlesNewIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/articles/$slug': typeof PrivateArticlesSlugRoute
  '/': typeof PrivateOverviewIndexRoute
  '/account': typeof PrivateAccountIndexRoute
  '/articles': typeof PrivateArticlesIndexRoute
  '/categories': typeof PrivateCategoriesIndexRoute
  '/newsletters': typeof PrivateNewslettersIndexRoute
  '/users': typeof PrivateUsersIndexRoute
  '/articles/new': typeof PrivateArticlesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_private/articles/$slug': typeof PrivateArticlesSlugRoute
  '/_private/_overview/': typeof PrivateOverviewIndexRoute
  '/_private/account/': typeof PrivateAccountIndexRoute
  '/_private/articles/': typeof PrivateArticlesIndexRoute
  '/_private/categories/': typeof PrivateCategoriesIndexRoute
  '/_private/newsletters/': typeof PrivateNewslettersIndexRoute
  '/_private/users/': typeof PrivateUsersIndexRoute
  '/_private/articles/new/': typeof PrivateArticlesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/articles/$slug'
    | '/account/'
    | '/articles/'
    | '/categories/'
    | '/newsletters/'
    | '/users/'
    | '/articles/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/articles/$slug'
    | '/'
    | '/account'
    | '/articles'
    | '/categories'
    | '/newsletters'
    | '/users'
    | '/articles/new'
  id:
    | '__root__'
    | '/_private'
    | '/_auth/sign-in'
    | '/_private/articles/$slug'
    | '/_private/_overview/'
    | '/_private/account/'
    | '/_private/articles/'
    | '/_private/categories/'
    | '/_private/newsletters/'
    | '/_private/users/'
    | '/_private/articles/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateUsersIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/newsletters/': {
      id: '/_private/newsletters/'
      path: '/newsletters'
      fullPath: '/newsletters/'
      preLoaderRoute: typeof PrivateNewslettersIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/categories/': {
      id: '/_private/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof PrivateCategoriesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/articles/': {
      id: '/_private/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof PrivateArticlesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/account/': {
      id: '/_private/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof PrivateAccountIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/_overview/': {
      id: '/_private/_overview/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateOverviewIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/articles/$slug': {
      id: '/_private/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof PrivateArticlesSlugRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/articles/new/': {
      id: '/_private/articles/new/'
      path: '/articles/new'
      fullPath: '/articles/new/'
      preLoaderRoute: typeof PrivateArticlesNewIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateArticlesSlugRoute: typeof PrivateArticlesSlugRoute
  PrivateOverviewIndexRoute: typeof PrivateOverviewIndexRoute
  PrivateAccountIndexRoute: typeof PrivateAccountIndexRoute
  PrivateArticlesIndexRoute: typeof PrivateArticlesIndexRoute
  PrivateCategoriesIndexRoute: typeof PrivateCategoriesIndexRoute
  PrivateNewslettersIndexRoute: typeof PrivateNewslettersIndexRoute
  PrivateUsersIndexRoute: typeof PrivateUsersIndexRoute
  PrivateArticlesNewIndexRoute: typeof PrivateArticlesNewIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateArticlesSlugRoute: PrivateArticlesSlugRoute,
  PrivateOverviewIndexRoute: PrivateOverviewIndexRoute,
  PrivateAccountIndexRoute: PrivateAccountIndexRoute,
  PrivateArticlesIndexRoute: PrivateArticlesIndexRoute,
  PrivateCategoriesIndexRoute: PrivateCategoriesIndexRoute,
  PrivateNewslettersIndexRoute: PrivateNewslettersIndexRoute,
  PrivateUsersIndexRoute: PrivateUsersIndexRoute,
  PrivateArticlesNewIndexRoute: PrivateArticlesNewIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
